spring.application.name=Gestion-Academica-App

# ==========================================
# CONEXIÓN A SQL SERVER
# ==========================================
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=BD_GESTION_ACADEMICA;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# NOTA: Si usas autenticación por usuario y contraseña de SQL Server,
# quita "integratedSecurity=true;" de la URL de arriba y descomenta estas líneas:
# spring.datasource.username=tu_usuario
# spring.datasource.password=tu_contraseña

# ==========================================
# CONFIGURACIÓN DE JPA E HIBERNATE
# ==========================================
# 'none' indica que Spring Boot NO debe intentar crear ni alterar las tablas.
# Esto es vital porque tú ya creaste un script muy bien estructurado en SQL Server.
spring.jpa.hibernate.ddl-auto=none

# Muestra en la consola de IntelliJ el código SQL que Spring ejecuta por debajo.
# Te servirá muchísimo para verificar qué está pasando cuando pruebes la app móvil.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Le indica a Hibernate que hable el "dialecto" exacto de SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect